repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
    exclude: (GLO-30-UTM-{{cookiecutter.utm_zone}}/|IW-UTM-RO-italy-{{cookiecutter.utm_zone}}-{{cookiecutter.relative_orbit}}/)
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: mixed-line-ending
# - repo: https://github.com/executablebooks/mdformat
#   rev: 0.7.17
#   hooks:
#   - id: mdformat
# - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
#   rev: v2.12.0
#   hooks:
#   - id: pretty-format-yaml
#     args: [--autofix, --preserve-quotes]
#     exclude: GLO-30-UTM-{{cookiecutter.utm_zone}}/
#   - id: pretty-format-toml
#     args: [--autofix]
