title = "earthdatahub-catalogue Gitleaks configuration"

[extend]
useDefault = true

[[rules]]
id = "earthdatahub-personal-access-token"
description = "Found a Earth Data Hub Personal Access Token"
regex = '''edh_pat_[0-9a-zA-Z]{96}'''
entropy = 3
keywords = ["edh_pat_"]

[[rules]]
id = "polytope-token"
description = "Found a Token likely used for Polytope access"
regex = '''eyJ[a-zA-Z0-9_-]{10,}\.eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}'''
entropy = 3
keywords = ["eyJ"]

[[rules]]
id = "cds-key"
description = "Found a CDS API Key"
regex = '''[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'''
entropy = 3
