# request
dataset: reanalysis-era5-single-levels
product_type: reanalysis
variables: [2m_temperature]
start_date: "1940-01-01"
stop_date: "2023-08-31"
area: []
engine: cdsapi
request_split: {day: 3}
cache_kwargs: {keep_file: false}
endpoint_url: https://s3.gra.perf.cloud.ovh.net/
storage_options: {client_kwargs: {endpoint_url: "https://s3.gra.perf.cloud.ovh.net"}, config_kwargs: {signature_version: s3v4}, default_block_size: 360000000}
request: {"collection_id": "{dataset}", "product_type": ["{product_type}"], "date": ["{start_date}/{stop_date}"]}

# storage & job management
tmp_bucket: data-access-dev
target_bucket: data-access-prod
job_dir: era5/single-levels
job_name: era5-single-levels-job.yaml
intermediate_rechunk_log_dir: intermediate_rechunk_log
final_rechunk_log_dir: final_rechunk_log
target_store_path: s3://{target_bucket}/era5/reanalysis-era5-single-levels-1940-2023.zarr
tmp_store_path: s3://{tmp_bucket}/{job_dir}/{dataset}-{variable}-1940-2023-tmp.zarr

# rechunk
target_chunks:
  lat: 32
  lon: 32
  time: 35064
tmp_chunks:
  lat: 256
  lon: 32
rechunk_batch_size: 36
