# request
dataset: reanalysis-era5-land
variables: [2m_temperature]
start_date: "1950-01-01"
stop_date: "2023-08-31"
engine: cdsapi
request_split: {day: 10}
cache_kwargs: {keep_file: false}
endpoint_url: https://s3.gra.perf.cloud.ovh.net/
storage_options: {client_kwargs: {endpoint_url: "https://s3.gra.perf.cloud.ovh.net/"}, config_kwargs: {signature_version: s3v4}, default_block_size: 120000000}

request: {collection_id: "{dataset}", date: ["{start_date}/{stop_date}"], area: ["73.99", "-27", "26", "44.99"]} #Europe

# storage & job management
tmp_bucket: data-access-dev
target_bucket: data-access-prod
job_dir: era5/land
job_name: era5-land-job.yaml
intermediate_rechunk_log_dir: intermediate_rechunk_log
final_rechunk_log_dir: final_rechunk_log
target_store_path: s3://{target_bucket}/era5/reanalysis-era5-land-europe-1950-2023.zarr
tmp_store_path: s3://{tmp_bucket}/{job_dir}/{dataset}-europe-{variable}-1950-2023-tmp.zarr

# rechunk
target_chunks:
  lat: 32
  lon: 32
  time: 35064
tmp_chunks:
  lat: 256
  lon: 32
rechunk_batch_size: 36
